name: Mobile App Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'mobile-app/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'mobile-app/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'mobile-app/package-lock.json'
    
    - name: Install dependencies
      run: cd mobile-app && npm ci
    
    - name: Run ESLint
      run: cd mobile-app && npx eslint --ext .js .

  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'mobile-app/package-lock.json'
    
    - name: Install dependencies
      run: cd mobile-app && npm ci
    
    - name: Run tests
      run: cd mobile-app && npm test

  build-android:
    runs-on: ubuntu-latest
    needs: [lint, test]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'mobile-app/package-lock.json'
    
    - name: Install dependencies
      run: cd mobile-app && npm ci
    
    - name: Setup Expo
      uses: expo/expo-github-action@v7
      with:
        expo-version: latest
        token: ${{ secrets.EXPO_TOKEN }}
    
    - name: Build Android app
      run: cd mobile-app && npx eas-cli build --platform android --profile preview --non-interactive

  build-ios:
    runs-on: macos-latest
    needs: [lint, test]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'mobile-app/package-lock.json'
    
    - name: Install dependencies
      run: cd mobile-app && npm ci
    
    - name: Setup Expo
      uses: expo/expo-github-action@v7
      with:
        expo-version: latest
        token: ${{ secrets.EXPO_TOKEN }}
    
    - name: Build iOS app
      run: cd mobile-app && npx eas-cli build --platform ios --profile preview --non-interactive