name: Web App Tests

on:
  push:
    branches: [ main ]
    paths:
      - '**.html'
      - '**.css'
      - '**.js'
      - '!mobile-app/**'
  pull_request:
    branches: [ main ]
    paths:
      - '**.html'
      - '**.css'
      - '**.js'
      - '!mobile-app/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run ESLint
      run: npx eslint --ext .js .
    
    - name: Run Stylelint
      run: npx stylelint "**/*.css"
    
    - name: Validate HTML
      run: npx html-validate "**/*.html"

  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test
    
    - name: Check for broken links
      run: npx broken-link-checker http://localhost:8080 --recursive --ordered --exclude linkedin.com --exclude facebook.com

  accessibility:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run accessibility tests
      run: npx pa11y-ci

  performance:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run Lighthouse CI
      run: |
        npm install -g @lhci/cli@0.11.x
        lhci autorun